name: Cross Compile CI
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            preset: ninja-multi-vcpkg
            triplet: x86-linux
            extra: '`-DCMAKE_C_COMPILER=i686-linux-gnu-gcc`, `-DCMAKE_CXX_COMPILER=i686-linux-gnu-g++`'
            setup: |
              sudo dpkg --add-architecture i386
              sudo apt-get update 
              sudo apt-get install -y \
              gcc-i686-linux-gnu \
              g++-i686-linux-gnu \
              libx11-dev:i386 \
              libgl1-mesa-dev:i386 libglu1-mesa-dev:i386 \
              libgl1-mesa-dev libglu1-mesa-dev
            env:
              CC: i686-linux-gnu-gcc
              CXX: i686-linux-gnu-g++
          - os: windows-latest
            preset: msvc-17-vcpkg
            triplet: x86-windows
            extra: '`-A`, `Win32`'

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          submodules: recursive

      - name: Setup
        run: ${{ matrix.setup }}

      - uses: lukka/get-cmake@latest

      - name: Restore from cache and setup vcpkg executable and data files.
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'

      - name: Run CMake+vcpkg to build packages.
        id: cmake-vcpkg-build
        uses: lukka/run-cmake@v10
        with:
          configurePreset: '${{ matrix.preset }}'
          configurePresetAdditionalArgs: "[`-DOPENBLACK_WARNINGS_AS_ERRORS=ON`${{ matrix.extra && format(', {0}, `-DVCPKG_TARGET_TRIPLET={1}`', matrix.extra, matrix.triplet) }}]"
          buildPreset: '${{ matrix.preset }}-debug'
          testPreset: '${{ matrix.preset }}-debug'

      - name: Upload .log files
        if: failure() && steps.cmake-vcpkg-build.outcome == 'failure'
        uses: actions/upload-artifact@v2
        with:
          name: log-files
          path: vcpkg/buildtrees/bgfx/*.log