name: Compiler Test
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - triplet: x86-linux
            os: ubuntu-latest
            preset: ninja-multi-vcpkg

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          submodules: recursive

      - run: |
            sudo apt-get update 
            sudo apt-get install -y \
                gcc-multilib
      - run: /usr/bin/cc test.c
      - run: /usr/bin/cc -m32 test.c
