name: Compiler Test
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - triplet: x86-linux
            os: ubuntu-latest
            preset: ninja-multi-vcpkg

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          submodules: recursive

      - run: |
            sudo apt-get update
            sudo apt-get install -y \
                gcc-multilib
            sudo dpkg --add-architecture i386
            sudo apt-get update
            sudo apt-get install -y \
                libx11-dev:i386 libxext-dev:i386 \
                libgl1-mesa-dev:i386 libglu1-mesa-dev:i386
      - run: /usr/bin/cc test.c -o test
      - run: /usr/bin/cc -m32 test.c -o test-32
      - run: file test*
